# Desativa conexões anônimas
allow_anonymous false

# Porta MQTT padrão
listener 1883

# Habilita WebSockets
listener 9001
protocol websockets

# Persistência
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

# Arquivo de senhas
password_file /mosquitto/config/passwd